AllCops:
  TargetRubyVersion: 2.6

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/FrozenStringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Security/Open:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Layout/LineLength:
  Max: 120
